database:
  # Database host address, default = localhost
  host: localhost
  # Database port, default = 3306
  port: 3306
  # Database name, default = minecraft
  database: minecraft
  # Database user, default = root
  user: root
  # Database password
  password: password
  # Connect to database over SSL, default = false
  enable-ssl: false
  # Overrides the size of the database connection pool, default = 10
  maximum-pool-size: 10
  # Connection timeout in milliseconds, default = maximum size of signed int
  connection-timeout: 5000

password:
  # Minimum length of the password required, default = 6
  minimum-length: 6
  # Maximum length of the password required, default = 64
  maximum-length: 64

# Time interval in seconds between two login reminder messages
reminder-message-frequency: 5

messages:
  already-registered: "<red>You are already registered.</red>"
  could-not-register: "<red>Could not register account.</red>"
  successfully-registered: "<green>Successfully registered.</green>"
  already-authorized: "<red>You are already authorized.</green>"
  could-not-authorize: "<red>Something went wrong with auto authenticating, please log in to authenticate manually.</red>"
  need-to-register-first: "<red>You need to register first.</red>"
  incorrect-password: "<red>Incorrect password.</red>"
  auto-authorized: "<green>You have successfully auto authenticated after registering.</green>"
  could-not-unregister: "<red>Could not unregister account.</red>"
  force-unregister: "<green>You have been unregistered by staff.</green>"
  successfully-unregistered: "<green>You have been successfully unregistered.</green>"