name: LizardAuth
version: 1.0.0
main: io.github.zrdzn.minecraft.lizardauth.LizardAuthPlugin
api-version: 1.17
authors: [Enixor]
description: Simple and secure authorization plugin for minecraft servers.
commands:
  register:
  unregister:
  login: